// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: basicpb/service.proto

package basicpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BizConfigs service

type BizConfigsService interface {
	GetBizConfigByKey(ctx context.Context, in *wrappers.StringValue, opts ...client.CallOption) (*BizConfigResult, error)
}

type bizConfigsService struct {
	c    client.Client
	name string
}

func NewBizConfigsService(name string, c client.Client) BizConfigsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "basic"
	}
	return &bizConfigsService{
		c:    c,
		name: name,
	}
}

func (c *bizConfigsService) GetBizConfigByKey(ctx context.Context, in *wrappers.StringValue, opts ...client.CallOption) (*BizConfigResult, error) {
	req := c.c.NewRequest(c.name, "BizConfigs.GetBizConfigByKey", in)
	out := new(BizConfigResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BizConfigs service

type BizConfigsHandler interface {
	GetBizConfigByKey(context.Context, *wrappers.StringValue, *BizConfigResult) error
}

func RegisterBizConfigsHandler(s server.Server, hdlr BizConfigsHandler, opts ...server.HandlerOption) error {
	type bizConfigs interface {
		GetBizConfigByKey(ctx context.Context, in *wrappers.StringValue, out *BizConfigResult) error
	}
	type BizConfigs struct {
		bizConfigs
	}
	h := &bizConfigsHandler{hdlr}
	return s.Handle(s.NewHandler(&BizConfigs{h}, opts...))
}

type bizConfigsHandler struct {
	BizConfigsHandler
}

func (h *bizConfigsHandler) GetBizConfigByKey(ctx context.Context, in *wrappers.StringValue, out *BizConfigResult) error {
	return h.BizConfigsHandler.GetBizConfigByKey(ctx, in, out)
}
